---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ggce
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Resolt/ArgoCDLearning.git
    targetRevision: HEAD
    path: ggce
  destination:
    server: https://kubernetes.default.svc
    namespace: ggce
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      # backoff:
      #   duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
      #   factor: 2 # a factor to multiply the base duration after each failed retry
      #   maxDuration: 3m # the maximum amount of time allowed for the backoff strategy