---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ggce-config
  namespace: ggce-ns
data:
  PORT: "8080"
  HOST: "0.0.0.0"
  GIN_MODE: "release"
  DB_HOST: "ggce-db.ggce-ns.svc.cluser.local"
  DB_NAME: "ggce"
  DB_USER: "ggce"
  DB_PASS: "ggce"
  DB_PORT: "5432"