---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: ggce
data:
  PORT: "8080"
  HOST: "0.0.0.0"
  GIN_MODE: "release"
  DB_HOST: "db.ggce.svc.cluster.local"
  DB_NAME: "ggce"
  DB_USER: "ggce"
  DB_PASS: "ggce"
  DB_PORT: "5432"