---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: ggce
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service
  namespace: ggce
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /ggce/
    - uri:
        prefix: /ggce
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 8888
        host: api
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: db
  namespace: ggce
spec:
  host: db.ggce.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 1s
        # tcpKeepalive:
        #   time: 30m
        #   interval: 60s