---
apiVersion: v1
kind: Service
metadata:
  name: ggce-api
  namespace: ggce-ns
spec:
  selector:
    app: ggce-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ggce-db
  namespace: ggce-ns
spec:
  selector:
    app: ggce-db
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432