---
apiVersion: v1
kind: Service
metadata:
  name: ggce-api
  namespace: ggce-ns
spec:
  type: NodePort
  selector:
    app: ggce-api
  ports:
    - port: 8888
      nodePort: 8888
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ggce-db
  namespace: ggce-ns
spec:
  selector:
    app: ggce-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP